### PR TITLE
Hotfix to adapt header for MM

### PR DESCRIPTION
**Pull request by zonky2**
Hotfix to adapt header for MM

tested in MM and Isotope

### CODE REVIEW

**Comment by stefanheimes** [comment]
Merge is done, corrections for travis, too. Please test it @zonky2 and let me know if erverythings works.

**Comment by zonky2** [comment]
at `table=tl_metamodel_dca_combine`works fine!

**Review by discordier — CHANGES_REQUESTED** [review]
Please change `key_exists()` to `array_key_exists()` as it has been renamed since PHP 4.0.6.

**Comment by zonky2** [comment]
I'm afraid you're too late - then only @stefanheimes  can change or I have to make a new PR - but it was like this in the original code

**Comment by discordier** [comment]
> I'm afraid you're too late - 

~How come? the PR is still open?~
Never mind, just saw it already got merged into hotfix.

> then only @stefanheimes can change or I have to make a new PR - but it was like this in the original code

I saw that but there is no reason to keep it broken when we are touching the code anyway, is there?

**Comment by zonky2** [comment]
> I saw that but there is no reason to keep it broken when we are touching the code anyway, is there?

Das Bessere ist der Feind des Gutem :D

**Pull request merged**
