### PR TITLE
Remove cca dependency and implement compatibility for Symfony ^4.4 || ^5.1

### LINKED ISSUE #107: Problem mit Contao 4.11.1 und Parameter "kernel.root_dir"
Guten Tag.

Ich habe gestern Abend eine Neuinstallation von Contao 4.11.1 über den Contao-Manager auf einem neuen VPS vorgenommen und bin über ein Problem gestolpert.

**Zum Selbermachen:**
1. Contao-Manager im /web Verzeichnis einrichten
2. Contao-Installation starten (bei mir wurde 4.11.1 geladen)
3. Im Contao-Manager zum Beispiel con4gis-Maps oder con4gis-Core installieren
4. Sobald die Installation durch ist kann auf contao/install oder contao/ generell nicht mehr zugegriffen werden > Fehler 500

**Ursache:**
```
src/DependencyInjection/MultiColumnWizardExtension.php
Zeile 66:             $container->getParameter('kernel.root_dir'),
```

Fehlerprotokoll /var/log/apache2/error.log:
```
[Wed Mar 10 22:45:03.708967 2021] [negotiation:error] [pid 4443] [client xxx] AH00687: Negotiation: discovered file(s) matching request: /var/www/html/contao/web/contao-manager (None could be negotiated)., referer: https://xxx/contao-manager.phar.php/
[Wed Mar 10 22:50:04.279689 2021] [php7:error] [pid 4441] [client xxx] PHP Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "kernel.root_dir". Did you mean one of these: "kernel.project_dir", "kernel.build_dir", "kernel.cache_dir", "kernel.logs_dir"? in /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:98\nStack trace:\n#0 /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php(61): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get()\n#1 /var/www/html/contao/vendor/symfony/dependency-injection/Container.php(118): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get()\n#2 /var/www/html/contao/vendor/menatwork/contao-multicolumnwizard-bundle/src/DependencyInjection/MultiColumnWizardExtension.php(66): Symfony\Component\DependencyInjection\Container->getParameter()\n#3 /var/www/html/contao/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(68): MenAtWork\ in /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php on line 98, referer: https://xxx/contao-manager.phar.php/
[Wed Mar 10 22:51:17.014626 2021] [php7:error] [pid 4442] [client xxx] PHP Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "kernel.root_dir". Did you mean one of these: "kernel.project_dir", "kernel.build_dir", "kernel.cache_dir", "kernel.logs_dir"? in /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:98\nStack trace:\n#0 /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php(61): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get()\n#1 /var/www/html/contao/vendor/symfony/dependency-injection/Container.php(118): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get()\n#2 /var/www/html/contao/vendor/menatwork/contao-multicolumnwizard-bundle/src/DependencyInjection/MultiColumnWizardExtension.php(66): Symfony\Component\DependencyInjection\Container->getParameter()\n#3 /var/www/html/contao/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(68): MenAtWork\ in /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php on line 98
[Wed Mar 10 22:53:20.471104 2021] [php7:warn] [pid 4441] [client xxx] PHP Warning: include(/var/www/html/contao/vendor/codefog/contao-haste/config/upgrade.php): failed to open stream: No such file or directory in /var/www/html/contao/app/Resources/contao/config/runonce.php on line 6, referer: https://xxx/contao-manager.phar.php/
[Wed Mar 10 22:53:20.471136 2021] [php7:warn] [pid 4441] [client xxx] PHP Warning: include(): Failed opening '/var/www/html/contao/vendor/codefog/contao-haste/config/upgrade.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/contao/app/Resources/contao/config/runonce.php on line 6, referer: https://xxx/contao-manager.phar.php/
[Wed Mar 10 23:06:33.865505 2021] [php7:error] [pid 4447] [client xxx] PHP Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "kernel.root_dir". Did you mean one of these: "kernel.project_dir", "kernel.build_dir", "kernel.cache_dir", "kernel.logs_dir"? in /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:98\nStack trace:\n#0 /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php(61): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get()\n#1 /var/www/html/contao/vendor/symfony/dependency-injection/Container.php(118): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get()\n#2 /var/www/html/contao/vendor/menatwork/contao-multicolumnwizard-bundle/src/DependencyInjection/MultiColumnWizardExtension.php(66): Symfony\Component\DependencyInjection\Container->getParameter()\n#3 /var/www/html/contao/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(68): MenAtWork\ in /var/www/html/contao/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php on line 98, referer: https://xxx/contao-manager.phar.php/
```

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #107

This also introduces proper Symfony dependencies and implements full compatibility with Symfony 4 and 5.

### CODE REVIEW

**Comment by zonky2** [comment]
@stefanheimes  took a look at it - the MCW must also remain usable for Contao 4.4 and therefore the PR cannot be adopted as it is.

However, the general problem is being worked on.

**Comment by fritzmg** [comment]
> @stefanheimes took a look at it - the MCW must also remain usable for Contao 4.4 and therefore the PR cannot be adopted as it is.

This PR has no effect on it being usable in Contao 4.4. After merging this PR, a new minor version should be released. You can then still provide bugfixes for the previous minor version, if you ever need to (which is unlikely anyway, as Contao 4.4 is outdated anyway and only gets security fixes).

**Comment by fritzmg** [comment]
> [zonky2](/zonky2) added this to the [4.0.0](/menatwork/contao-multicolumnwizard-bundle/milestone/3) milestone [yesterday](#event-5190785495)

This must not be released as a new major version. If you do, it would not resolve the original issue.

**Comment by zonky2** [comment]
> This must not be released as a new major version. If you do, it would not resolve the original issue.

I only do the "secretary job" - that's up to @stefanheimes

**Comment by fritzmg** [comment]
Then may be @stefanheimes should join this discussion here 😁

**Comment by stefanheimes** [comment]
Question @fritzmg: Why adding symfony/http-foundation or symfony/http-kernel as requirement. We didn't use them. So why adding more blocker to the list of requirements than needed? Why should I add all the sub requirements to the list, I'm only interested in the direct requirements and the result from them and not for the second or third sublevel requirement in the list.

**Comment by fritzmg** [comment]
> Why adding symfony/http-foundation or symfony/http-kernel as requirement. We didn't use them.

You are using these components here:

* https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/298df573d669446d8d40605fc014a9cf98052c8b/src/EventListener/BaseListener.php#L76
* https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/298df573d669446d8d40605fc014a9cf98052c8b/src/MultiColumnWizardBundle.php#L34
* https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/298df573d669446d8d40605fc014a9cf98052c8b/src/EventListener/Contao/ExecutePostActions.php#L118
* https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/298df573d669446d8d40605fc014a9cf98052c8b/src/EventListener/Contao/ExecutePostActions.php#L128
* https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/298df573d669446d8d40605fc014a9cf98052c8b/src/EventListener/Contao/ExecutePostActions.php#L233
* https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/298df573d669446d8d40605fc014a9cf98052c8b/src/EventListener/Contao/ExecutePostActions.php#L255
* https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/298df573d669446d8d40605fc014a9cf98052c8b/src/EventListener/Contao/ExecutePostActions.php#L367
* https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/298df573d669446d8d40605fc014a9cf98052c8b/src/EventListener/Mcw/CreateWidget.php#L75

> So why adding more blocker to the list of requirements than needed? Why should I add all the sub requirements to the list, I'm only interested in the direct requirements and the result from them and not for the second or third sublevel requirement in the list.

These are direct dependencies. Sure, both the `http-foundation` and `http-kernel` will likely always already be there, since they are used by Contao. But the same assumption was made for `sensio/framework-extra-bundle` for example and then when Contao did not need that package anymore, extensions broke because they did not properly require their dependencies.

Furthermore extensions broke because they did not properly require `symfony/dependency-injection` in the correct version.

And similarly extensions broke because they did not properly require `symfony/config` in the correct version.

Especially the latter is a problem that is still present in many extensions today. So imho either you properly require _all_ your actual dependencies, or you live with the fact that you might have to hotfix something, once one of these dependencies change in an incompatible way in newer versions (or if it gets dropped altogether).

Also the fact that `menatwork/contao-multicolumnwizard-bundle` was missing the dependency for `symfony/http-kernel` in the appropriate version is what was causing the problem in https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/107 in the first place. No issue would have occurred, if for example `symfony/http-kernel: ^3.0 || ^4.0` was defined as a dependency. Yes, it turned out later that the troublesome code was not necessary anyway and was subsequently removed in 1e0db7c3fd4cfb30a1863d739e8020314cddaf0c - but that's beside the point.

And these dependencies do not really block anything for Contao 4, as the switch to Symfony 6 will not happen for Contao 4.

**Comment by stefanheimes** [comment]
@fritzmg Thanks for the help. My problem was I had used the package name instead of the right Namespace for the search. So I totally missed this things. You are right it would be much better to add the requirements, so that we always have what we need.

All looks okay, I think I will make a new 3.5. There are no API breaks, only the argument change for the events dispatcher :P

**Comment by fritzmg** [comment]
> There are no API breaks, only the argument change for the events dispatcher :P

Yes, this was changed in Symfony 4, with BC to the old Symfony 3 way. In order to be compatible with Symfony 4 and 5 though, only the new way works (event object as first argument, optional event name as second).

But this does not break the MCW API.

**Comment by stefanheimes** [comment]
@fritzmg I have merged this PR into dev, which is the pre version for the 3.5.0. Can you test if everthing is working for you ?

**Comment by fritzmg** [comment]
Everything seems to work fine as far as I tested 👍

**Comment by fritzmg** [comment]
@zonky2 @stefanheimes any chance to get this released as `3.5.0` soon? The problem keeps piling up on the forum and in Slack ;)

**Comment by zonky2** [comment]
its @stefanheimes turn...

**Comment by stefanheimes** [comment]
I have added a new support/contao4.4 branch. 
I merged all changes from dev into master with the new version 3.5.0.
I replaced all the branch alias entries with the right ones. 

@fritzmg @zonky2 should be fine now :)

**Comment by stefanheimes** [comment]
@fritzmg by the way, do you see any problem with this pr #112 if I merge this in ther current 3.5.0 branch ?

**Comment by fritzmg** [comment]
> @fritzmg by the way, do you see any problem with this pr #112 if I merge this in ther current 3.5.0 branch ?

Should be fine, but it was not merged correctly: https://github.com/menatwork/contao-multicolumnwizard-bundle/pull/114

**Pull request merged**
