### PR TITLE
Fix post ajax contao name changes

### PR DESCRIPTION
**Pull request by Aziz-JH**
I found a workaround for the contao FileTree and PageTree widgets changes from https://github.com/contao/contao/commit/279f94c74d820b8717a2e7a7672e67786646563e

Issue: https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/51#issuecomment-539605216

I test it on Contao 4.8.4 with single and multi edit.

### CODE REVIEW

**Comment by discordier** [comment]
According to https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/51#issuecomment-552391278 this does not work in Contao 4.4.44?

@Stefanmelz is this the version you checked?

**Comment by Stefanmelz** [comment]
> According to [#51 (comment)](https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/51#issuecomment-552391278) this does not work in Contao 4.4.44?
> 
> @Stefanmelz is this the version you checked?

Yes

**Comment by Aziz-JH** [comment]
@Stefanmelz thank you for your feedback, can you recheck my last changes? I forget, there is in Contao not just a version number, there are also a build number.

**Comment by therouv** [comment]
I just ran into the same issue when using Contao 4.8.5. I've applied this patch locally and can confirm that it fixes the issue. Would be great if this PR could be merged :-)

**Review by discordier — APPROVED** [review]
LGTM

**Pull request merged**
