### PR TITLE
[WIP] Fix generate tableless generation

### PR DESCRIPTION
**Pull request by Aziz-JH**
If you use `generateTableless` there is an bug that prevents the fields from being generated.

### CODE REVIEW

**Comment by Aziz-JH** [comment]
ok, there are more problems with the tableless variation. It's not possible to use it.
The .js logic is just for the table variation written

https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/8199ad34029a7687c1a4436ae95974fd8dc81e18/src/Resources/public/js/multicolumnwizard_be_src.js#L84

https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/8199ad34029a7687c1a4436ae95974fd8dc81e18/src/Resources/public/js/multicolumnwizard_be_src.js#L322
...

**Comment by discordier** [comment]
So this is to be considered to be a WIP and not ready to merge yet.

@Aziz-JH will you continue on this and revamp the JS as well?

**Comment by Aziz-JH** [comment]
Oh ok, this is WIP. Is a feature brunch for something like this not better?
@discordier I can look in to it, but for which case would `generateTableless` be good?

**Comment by zonky2** [comment]
@Aziz-JH 
may be you change `tbody`, `tr` and `td` as css classes and change the table template - now you can build the same table with div containers

**Comment by zonky2** [comment]
@Aziz-JH pls check Travis and change your code

**Review by discordier — CHANGES_REQUESTED** [review]
Needs to be finished

**Pull request closed without merging**
