### PR TITLE
Add PHP8 array isset checks

### PR DESCRIPTION
**Pull request by bytehead**
Fixes some `undefined array key` warnings:

image (2)

Removed PHP 5.6 support (as this commit https://github.com/menatwork/contao-multicolumnwizard-bundle/commit/05d2917208d08f4fe63961bd4108d63a2c3f6420 introduced PHP 7 features)

### CODE REVIEW

**Comment by creo-code** [comment]
Shouldn't there be a check for line 1115, 1401 and 1416 too?

- [MultiColumnWizard.php#L1115](https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/14d0fd7c0384809bedcd5c552670186f8e9e68a1/src/Contao/Widgets/MultiColumnWizard.php#L1115)
- [MultiColumnWizard.php#L1401](https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/14d0fd7c0384809bedcd5c552670186f8e9e68a1/src/Contao/Widgets/MultiColumnWizard.php#L1401)
- [MultiColumnWizard.php#L1416](https://github.com/menatwork/contao-multicolumnwizard-bundle/blob/14d0fd7c0384809bedcd5c552670186f8e9e68a1/src/Contao/Widgets/MultiColumnWizard.php#L1416)

**Comment by bytehead** [comment]
@creo-code you're possibly right. but there is no reaction from the maintainers since days anyway.

**Comment by bytehead** [comment]
@creo-code Added in fe57d73.

**Comment by creo-code** [comment]
> @creo-code Added in [fe57d73](https://github.com/menatwork/contao-multicolumnwizard-bundle/commit/fe57d73dd56e9a5d9d7fa8845b17ae37d5a9e74a).

Works for me with PHP8 👍

**Comment by Xirdion** [comment]
Are there any news when the PR will get merged. By now it's quite difficult to work with the extension if dev mode is active.

**Comment by bytehead** [comment]
Use `composer selfupdate 2.2.9` until then 😎

**Comment by bytehead** [comment]
You could adjust the php error level:  `contao.error_level: 8181`

**Comment by stefanheimes** [comment]
Merged and fixed in https://github.com/menatwork/contao-multicolumnwizard-bundle/releases/tag/3.5.3

**Pull request closed without merging**
